### ISSUE TITLE
Will not open

### ISSUE THREAD

**Issue by jhasselbach22** [MrPrimate/tokenizer#102]
Hello,

Running Foundry V.10 Build 286 latest build with Pathfinder 4.1.2 (just updated) and Tokenizer will not open via clicking on character portraits or in the title.

Just tested my D&D world and it works fine so I think it's a Paizo/Pathfinder specific issue.

Any help is appreciated!

Thank you!

**Comment by MrPrimate** [comment]
This works for me. Can you try disabling other modules (Find the Culprit can help with this) and see if it works?

If it still doesn't please open the console (F12) and see if any errors appear.

**Comment by jhasselbach22** [comment]
Thank you for your response. I did disable the other modules as well with Tokenizer being the only module active with no luck as well. 

The following error that I am seeing is this:

![3](https://user-images.githubusercontent.com/8021443/192012721-f33a8585-0c47-43a8-b4b7-043f3dfbbbf0.JPG)
![2](https://user-images.githubusercontent.com/8021443/192012768-00b89b06-456e-4100-ac6f-c630b67466c9.JPG)

**Comment by jhasselbach22** [comment]
Disregard, I reset all settings back to default setting and it is fine, I am a moron.

Thank you very much!!

**Comment by MrPrimate** [comment]
It might be that it got stuck trying to open a dir or something like that
