### ISSUE TITLE
[Feature Request] Auto-center button for layers

### ISSUE THREAD

**Issue by Malkyn99** [MrPrimate/tokenizer#111]
Title. Trying to make a token where the wings go beyond the token borders, doing it by trying to shrink the base frame and then upping the scale, but when things get their size changed, they don't recenter, which makes it a matter of trial and error to recenter when upscaling. Was wondering if an auto-center button could be added to each layer.

**Comment by MrPrimate** [comment]
In v4.2.2, thanks for the suggestion.
