### ISSUE TITLE
[Feature Request] Download Button

### ISSUE THREAD

**Issue by jbblanchet** [MrPrimate/tokenizer#113]
Your tokenizer is so good and useful that I want to use it for stuff outside of foundry. Would it be possible to add a "download" button so that I can download the resulting file locally without having to save it on the server?

Thanks for all your hard work, your tool is a joy to use.

**Comment by MrPrimate** [comment]
This is now in v3.11.0

**Comment by jbblanchet** [comment]
Fantastic! Can't wait to try it!
