### ISSUE TITLE
Tokenizer Window does not open (Tokenizer V 3.9.3, FVTT 0.7.10)

### ISSUE THREAD

**Issue by cube1us** [MrPrimate/tokenizer#117]
The tokenizer module installs, and items appear on the drop down menu.  However, clicking (or shift clicking, if it is set that way) does NOT open the tokenizer dialog, either on the native PC application screen, nor in a browser.  

(I would love to upgrade FVTT but I can't until V10 is stable because the Scenery module I use was abandoned after 0.7.10, but looks like it will be supported under V10)

In a browser, the following error is thrown:

hooks.js:31 Uncaught TypeError: Cannot read properties of undefined (reading 'layers')
[Detected 1 package: vtta-tokenizer]
    at launchTokenizer (hooks.js:31:15)
    at tokenizeActor (hooks.js:95:3)
    at tokenizeDoc (hooks.js:126:5)
    at HTMLImageElement.<anonymous> (hooks.js:265:15)
    at HTMLImageElement.dispatch (jquery.min.js:2:43090)
    at v.handle (jquery.min.js:2:41074)
launchTokenizer @ hooks.js:31
tokenizeActor @ hooks.js:95
tokenizeDoc @ hooks.js:126
(anonymous) @ hooks.js:265
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2

**Comment by MrPrimate** [comment]
Sorry I won't be releasing another v7 compatible version, you can maybe try finding an older version in the release history and installing it via the manifest link https://github.com/MrPrimate/tokenizer/releases then pinning the package.

**Comment by cube1us** [comment]
Thanks.  3.4.0 Seems to work OK.  3.5.0 and up do not seem to work (I only tried the .0 releases at this point)
