### ISSUE TITLE
Import more tokens rings

### ISSUE THREAD

**Issue by gatesvp** [MrPrimate/tokenizer#120]
Somebody opened up some tokens for use on Reddit.
https://www.reddit.com/r/BattleTokens/comments/115upoi/token_border_collection_oc/

Looks like they have [high-res versions ](https://www.reddit.com/r/BattleTokens/comments/115upoi/comment/jc5v1ed/?%2524deep_link=true&correlation_id=5d2f6fbc-9bc1-4592-95fd-f4082c603dbd&ref=email_comment_reply&ref_campaign=email_comment_reply&ref_source=email&%25243p=e_as&_branch_match_id=998156070990510118&utm_medium=Email%20Amazon%20SES&_branch_referrer=H4sIAAAAAAAAA31O0WrDMAz8Gu8tSWPHYRmUsVL2BXs3jqy0bh3bKM7C%2Fn7K1r0OJDjp7qS7lpKXl6YhdM6X2uZcBx%2FvjcqvQnYqH9HY5YlhIn%2Fx0QazUjhed5dQb0K%2Bc23bVj%2F8kGZeEPfJlhLwI90xLjwyMWMsO2xbvebkGZWdNWMih2QghYBQfIomAZM30J8tuv2F4i%2BdQ8xmzybUudCKQvaQiDDYH493vNdOTv00QjWM0FadHmQ16MlVU3d4ltAflBv5YE84sRhn64N5BDOEOXz9cgbsnK2%2FxH9FS1oJ8E%2FyDVrBhzVIAQAA) that we can incorporate.

**Comment by MrPrimate** [comment]
Added in v3.10.2
