### ISSUE TITLE
[Feature Request] Adding multiple masks

### ISSUE THREAD

**Issue by kristkos** [MrPrimate/tokenizer#122]
Well as the title states, 

The ability to select multiple layers of masks, and be able to swap them freely (from a selector similar to the frames)

To provide an example, using Image A(token ring image) at the bottom, using a transparent image with the artwork middle, using Image A again only to mask 50% of the designated artwork to create a bit of depth. Everything below the red line to be under said token

![image](https://user-images.githubusercontent.com/106399251/229527996-e026f259-5377-44fd-8567-65a29a7f6f1a.png)

**Comment by MrPrimate** [comment]
I have started to add support for this in v3.11.0, although it doesn't _quite_ do precisely what you want yet, it should add a few more tools to your arsenal.

**Comment by MrPrimate** [comment]
Available in v4.0.1
