### ISSUE TITLE
Multi Mask Order

### ISSUE THREAD

**Issue by brunocalado** [MrPrimate/tokenizer#123]
Hi

Is it possible to select where mask will work? 

Example:
I want the upper frame part to me bellow the main image and the lower frame part be above the image.

So, this is what I want:
![Sem Título-1](https://user-images.githubusercontent.com/4999783/230798108-d17ab50b-62cd-4f62-95b4-ee554cba33d1.png)

But, I couldn't find a way to do this inside tokenizer.
![image](https://user-images.githubusercontent.com/4999783/230797645-b70be19d-0956-42bd-ac8f-db1bd1d545e2.png)

**Comment by MrPrimate** [comment]
Related to #121.

This is coming soon, hopefully!

**Comment by MrPrimate** [comment]
Available in v4.0.1
