### ISSUE TITLE
Add Layer closes interface instead.

### ISSUE THREAD

**Issue by AlanDNelson** [MrPrimate/tokenizer#126]
https://user-images.githubusercontent.com/36895037/232558205-e8b12a00-3dd5-4ef9-af1d-cab5231f0230.mp4

I am trying to add a layer... but the interface just closes instead.

Almost all other modules deactivated (Module Compatibility Checker and Module Management +)

**Comment by MrPrimate** [comment]
Ah! So that button shouldn't be a button, please use the options next to it, and I'll get that fixed for the next release

**Comment by MrPrimate** [comment]
Fixed in v4.02

**Comment by AlanDNelson** [comment]
Glad to help!  Thanks for your work.  I shudder to think about game-prep
without Tokenizer on my list of tools!  =)


     - Alan
