### ISSUE TITLE
[Feature Request] Duplicate Layer

### ISSUE THREAD

**Issue by brunocalado** [MrPrimate/tokenizer#129]
Hi.

Can you add an option to duplicate a layer?

Example:
I have change the position and size of this art. I need to add it again and match the position and size from the first art. If I had a duplicate button I could just duplicate the first layer without change of mismatch the position.
![image](https://user-images.githubusercontent.com/4999783/233630331-3a0d4610-c246-43f4-b142-1222ec50b18c.png)

tks

**Comment by MrPrimate** [comment]
Thank you, this will be in v4.0.4, which will be out within a few days.
