### ISSUE TITLE
Custom Frames Fail to Mask, Layers are completely Hidden while default frames work fine

### ISSUE THREAD

**Issue by KellethDregar** [MrPrimate/tokenizer#132]
It seems this issue is occurring again: https://github.com/MrPrimate/tokenizer/issues/80

Token frames seem to not apply a mask layer and will obscure the entirety of the layer below. It seems to still be working with the last version 4.1.1

V 4.1.2
![image](https://user-images.githubusercontent.com/79947702/235421209-f3b3328b-1ff6-4972-a860-c45c5e9cd5a6.png)

V 4.1.1
![image](https://user-images.githubusercontent.com/79947702/235421365-cef188ae-b68c-4368-a252-f15f86022d29.png)

**Comment by MrPrimate** [comment]
Can you explain the process you're using to add a frame? Is this the default frame? Added via add image? Or via the add frame button?

**Comment by KellethDregar** [comment]
The above scenarios were both done with the "Upload from your computer" functionality. I tested with a variety of token borders, it seems any uploaded don't get properly masked. I tried with Ray Algorithm on and off to no avail.

When using one of the default frames under the add frame button that seems to work in both versions.

**Comment by MrPrimate** [comment]
Okay, the workflow I expected here would be Add Frame -> Select Another File -> then upload your custom frame to the foundry server.

I will need to make a tweak to accommodate applying the default masking algorithm to files uploaded using the other button.

**Comment by KellethDregar** [comment]
Ah ok that makes sense, thank you!

**Comment by KellethDregar** [comment]
Hi @MrPrimate quick question was this tweak ever made to allow masking in this method?

**Comment by MrPrimate** [comment]
Oh sorry, I made some changes to fix this a while ago but got distracted, please find the final pieces in v4.2.5, available in all good Foundry updaters now.
