### ISSUE TITLE
When editing previously saved mask, can add (left click) but cannot remove (right click)

### ISSUE THREAD

**Issue by nguyenjessev** [MrPrimate/tokenizer#134]
When editing an existing mask that was previously saved, if I right click to remove areas and then apply, the changes do not apply. If I try to add to the mask using left click, those changes apply successfully

Here's a gif of the issue happening:
![giphy](https://github.com/MrPrimate/tokenizer/assets/67484662/48e8a15e-6566-4340-95ec-8c412444cf0b)

**Comment by MrPrimate** [comment]
Are you using the most recent version?, because it's supposed to fix this issue!

**Comment by nguyenjessev** [comment]
Aha, that was it! I didn't realize that a new version had been released. Thanks!
