### ISSUE TITLE
[Feature Request] Allow scaling by percentages

### ISSUE THREAD

**Issue by tuhs1985** [MrPrimate/tokenizer#135]
Pretty simple, allow for scaling by percentages rather than just a mouse wheel.  Allows for more consistent outputs, especially if an auto center feature were added.  i.e. If I scaled the token frame down 50%, then I know how to adjust my token scale to account with the additional padding - easier to do with an auto center feature but the mk80 eyeball isn't to bad for this.

**Comment by MrPrimate** [comment]
Now in v4.2.3
