### ISSUE TITLE
Token sizing issue after completing

### ISSUE THREAD

**Issue by kristkos** [MrPrimate/tokenizer#138]
I am a bit unsure how to describe it, however I will provide pictures with each step, and attach the artwork I am using.

Step one:
Upload the avatar and the layers needed, create an alpha for the elements that need to be on top:
![image](https://github.com/MrPrimate/tokenizer/assets/106399251/0b717854-bb8d-4811-a9d8-ebd4546c55e8)

Step two:
Apply changes, and drop the token on the canvas, and it displays correctly on the canvas, if I reopen tokenizer, it looks @75% in size:
![image](https://github.com/MrPrimate/tokenizer/assets/106399251/22b7a59b-fecc-4994-be46-6f59abe8de05)

I am submitting a bug request, as under the regular circumstances this wouldn't had affected me, however, after a while, the already modified token for both the avatar and the token do change. The transparent background disperses and the token keeps shrinking, and this does happens on the canvas too

No edits:
![image](https://github.com/MrPrimate/tokenizer/assets/106399251/c71f665d-d9a0-4f01-8292-b0ed21aa5530)

![image](https://github.com/MrPrimate/tokenizer/assets/106399251/0cfff4ff-f438-46ae-bb09-589d6551e827)

Picture used: 
![Forsaken 1](https://github.com/MrPrimate/tokenizer/assets/106399251/12c75f90-30fd-4351-82d2-d5e60e13585c)

**Comment by MrPrimate** [comment]
This is the "Default Token Offset" option, which defaults to -35. Change this to 0 and your image won't be shrunk on opening Tokenizer. You can also remove the default colour layers and token layer if you need to here as well.
