### ISSUE TITLE
Why is there a white background by default and how do I get rid of it

### ISSUE THREAD

**Issue by Asherlock** [MrPrimate/tokenizer#141]
I cant seem to get rid of this extra layer here. All the tutorials I've looked at don't seem to have it and I'm not sure why it's there... any help?
![image](https://github.com/MrPrimate/tokenizer/assets/15909275/406db63d-b581-4752-a26f-123fd2e05f37)

**Comment by MrPrimate** [comment]
In this example given, I don't believe there is a white layer, the white box you are pointing to is a visual display of the mask selection for the current layer.

The white around the edge of the token you are seeing here is from the token image.

It looks like you have reopened a previously edited token?

Tokenizer doesn't remember the previous configuration of layers when editing a token, all this information gets discarded when you save and it creates the image for you.


When you open it tokenizer by default it will shrink the token ( see https://github.com/MrPrimate/tokenizer/issues/138 ), add the default token ring, and add a image layer of pure colour (you can disable this by selected "Add a color layer by default" in the module settings. It's default settings will generate a result such as:


![Screenshot from 2023-09-03 08-46-09](https://github.com/MrPrimate/tokenizer/assets/3985378/0bfd1562-f0c1-45cd-b2b7-b1817db633cc)
