### ISSUE TITLE
yzecoriolis system switch to the standard img field for character art

### ISSUE THREAD

**Issue by coderunner** [MrPrimate/tokenizer#147]
In one of the recent update, the yzecoriolis system switch to use the standard img field instead of system.keyArt for the character art.

This prevents the module from working properly since there is a special case for yzecoriolis https://github.com/MrPrimate/tokenizer/blob/master/src/hooks.js#L17.

**Comment by MrPrimate** [comment]
Thanks for the heads up! Fixed in v4.2.11
