### ISSUE TITLE
Support new dynamic rings

### ISSUE THREAD

**Issue by Sinled** [MrPrimate/tokenizer#153]
Hi, maybe such thing already exist but i couldn't find it, it would be nice to have some preset that will allow quickly crop and/or apply dynamic token rings from tokenizer.

You can do it now manually by applying mask, and then hiding ring, but it takes some time.

**Comment by MrPrimate** [comment]
This is now possible with the new Add Mask option, which includes two masks that fit the dynamic ring.

You can disable the add frame and enable Add Mask in tokenizer settings to ensure that the default or chosen maak is added instead of a ring when opening Tokenizer.

**Comment by Sinled** [comment]
Thanks, it works!
