### ISSUE TITLE
Allow non-square avatar art

### ISSUE THREAD

**Issue by yorkshirelandscape** [MrPrimate/tokenizer#156]
If you use Tokenizer even just to edit the Token without touching the avatar art, it will crop your avatar art to a square image which, to me, is never desirable. I would recommend only changing the avatar art if it is edited within Tokenizer. It might be nice, alternatively, if Tokenizer allowed you to save non-square avatar art.

**Comment by MrPrimate** [comment]
Tokenizer will only adjust the avatar art if you have the `Modify` checkbox selected above the Avatar image.

To upload and keep art as the original upload/size/shape then you can shift click on the avatar image on the character sheet to bypass Tokenizer.

**Comment by MrPrimate** [comment]
If tokenizer is opening with the the Modify checkbox ticked by default for your avatar, make sure "Token only default" is checked in the module settings (this is the default value)

**Comment by yorkshirelandscape** [comment]
Ah that's great to know. Thank you!

Btw, have you ever considered offering the option of uploading to something like imgur and hotlinking the art? I bet that would be a popular option with Pathfinder Society and Adventure League players.
