### ISSUE TITLE
Render time in 1 world

### ISSUE THREAD

**Issue by Sarge95k** [MrPrimate/tokenizer#163]
V11 DnD5e
Disabled all modules bar Tokenizer and issue persists.
In World 1, Tokenizer takes 40+s to load its window with all modules enabled or disabled.
In World 2 with all modules enabled or disabled Tokeniser loads in 2 seconds.

Console only states render beggining and suggests willReadFrequently attribute be set to true and that is all.

**Comment by MrPrimate** [comment]
Can you try resetting your tokenzer settings in the bad world:

Use the dev console (F12) or create a script macro:

```javascript
game.settings.settings.forEach((s) => {
  if (s.namespace !== "vtta-tokenizer") return;
  game.settings.set(s.namespace, s.key, s.default);
});
```

**Comment by Sarge95k** [comment]
This has worked, tyvm
I had tried turning off and uninstalling tokenizer
then reinstalling
re-enabling but the issue persisted

This Macro has indeed fixed the issue, which i think means likely something on my machine certainly broke it.
