### ISSUE TITLE
[Suggestion] PF2e Scaled Mask for Dynamic Rings

### ISSUE THREAD

**Issue by 117ksk** [MrPrimate/tokenizer#170]
In the current version of the PF2e system for Foundry v12, all medium creature default token size fills the entire square. All premium content monster tokens, bestiary packs etc. all use the full square to depict the size of a medium creature. The new dynamic rings introduced in Foundry v12 expect a medium sized creature to use a token that fills only about 20% of the square. This means that if you want to make medium sized player character tokens in a PF2e game, you must scale up the dynamic token ring by setting the scale to 0.8 instead of the default 1.0. 

When using Tokenizer masking for dynamic tokens, the mask file used is meant for 1.0 token scaling and not 0.8. This results in a masked image that is too small for the scaled up tokens for PF2e. A solution I am using is using a custom mask file in Tokenizer that is just the default circle mask scaled up 20%.

My suggestion would be to include a similar mask file in the Tokenizer module files that can be utilized for everyone that is making tokens for PF2e and intend to scale the dynamic token rings to match that of all other tokens in the system. 

Additionally, this scaled up mask file could be set as default as par of the new quick settings menu in Tokenizer settings for PF2e players.

**Comment by MrPrimate** [comment]
I believe this will now work with the grid scaling in the latest version of foundry and tokenizer.
