### ISSUE TITLE
Error when right-clicking compendium search result

### ISSUE THREAD

**Issue by ThiefMaster** [MrPrimate/tokenizer#172]
```
15:49:29.898 Uncaught TypeError: compendium is undefined
    condition .../modules/vtta-tokenizer/dist/main.js:7396
    render .../scripts/foundry.js:64900
    bind .../scripts/foundry.js:64824
```

For me this happened both on a fully up to date Foundry 12 (with all modules update to the latest version) and on a slightly older Foundry 11. In both cases it's a pf2e world, and I searched for the "Physician" NPC (but it probably also happens for anything else, that was just the one I was searching for for an unrelated reason).

**Comment by MrPrimate** [comment]
Fixed in v4.3.12, out shortly, thank you for this report.
