### ISSUE TITLE
[Feature/Bug] Supprot for Grid Fit

### ISSUE THREAD

**Issue by ChasarooniZ** [MrPrimate/tokenizer#174]
Hi, the reason why grid fit breaks tokenizer's old mask is it sets the token image, not `subject texture`. Maybe either make the feature that enables dynamic tokens when you save also cause the image to set the  `subject texture`, or make that it's own option?

**Comment by MrPrimate** [comment]
Please explain the problem more, ideally with steps to reproduce.

**Comment by ChasarooniZ** [comment]
Hi, sorry:

With the new update that allows grid fit, you have offered the following mask options:
- `Grid Fit Dynamic Mask`
- `Normal Dynamic Mask`

However this only solves a symptom not the root of the problem:

(The problem being, when switching your Dynamic Ring Fit, it requires resizing the Dynamic Ring to based on how you made it)

Step by step explanation of process that would fix the issue
- Has setting in tokenizer that allow you to save the tokenizer result as the Dynamic Ring `Subject Image`
- Make token using the default dynamic ring mask
- Saves output
- this gets added as the Token's Dynamic Ring `Subject Art` (Foundry only does the grid fit scaling on this not on the regular `Token Art` that it falls back to if the `Subject Art` isn't available for some reason)
- Now the Art will work regardless of which toggle you have active


(Hopefully that makes more sense?)


Without this, you'd need to make 2 separate arts for each Dynamic Ring Type as opposed to one for both

**Comment by MrPrimate** [comment]
Thank you for bringing this to my attention, fixed for you in the latest release.
