### ISSUE TITLE
[bug] Layers are forgotten in the token and regenerated from the combined token image on edit

### ISSUE THREAD

**Issue by cblegare** [MrPrimate/tokenizer#177]
Repro step:

- pick an avatar.
- create token with 2 layers
  - Frame
  - image from avatar
- Apply
- open the token editor again
- There is now three layers
  - Frame
  - Image which is the whole token previously saved
  - a white layer
  
It basically combines all layers and use that to generate three new layers on the next edit.

If you open and apply the editor (without any changes) a few times, you end up with multiple frames:
 
 
![image](https://github.com/user-attachments/assets/03d73481-9091-4d21-9244-5babdc66700d)

**Comment by MrPrimate** [comment]
Tokenizer doesn't save you're previous layers etc, it's not a full image editor, just a quick tool for making tokens.

If you wish to disable the offset of the existing token size and addition of the token ring when you open, you can change these options in the settings so it adds the layers you wish to see.

The quickest way to do this is to select the "Quick Settings Selector" in the tokenizer settings, and then "Nothing" as the option.
