### ISSUE TITLE
some frames won't mask correctly

### ISSUE THREAD

**Issue by modzy2** [MrPrimate/tokenizer#49]
I have these two PNG's.  good.png behaves as expected when using the Mask button.

bad.png looks ok if it's layered on top of another image (I can see through inside the ring) but the mask button removes the outside around the ring as expected, but it also removes the visible next layer from inside the ring also.

[bad.png](http://www.emptypod.net/bad.png)
[good.png](http://www.emptypod.net/good.png)

**Comment by MrPrimate** [comment]
Resolved in v3.8.3
