### ISSUE TITLE
[Feature/Change Request] Make "Center Layer" not also revert resizing, or make zoom not linked to cursor

### ISSUE THREAD

**Issue by asherett** [MrPrimate/tokenizer#53]
Currently, the "Center Layer" buttons not only center the layer, but also revert all resizing. 
Since the "zoom" function (mouse wheel) is currently linked to mouse cursor position, it's easy to get the image off-center by accident when resizing. Currently there's no easy way to maintain zoom while keeping the image centered.

So I'm requesting one of two changes:

1) Either make the "Center Layer" button only actually center the layer, not also revert zoom
or
2) Make the mousewheel scroll zoom not care about cursor position, so it always zooms in/out to center.

**Comment by MrPrimate** [comment]
I've renamed this to "Reset layer" for now, but I'll have a think about the best way to get centering in, and where to place the button!
