### ISSUE TITLE
[Feature request] Default background image

### ISSUE THREAD

**Issue by SalieriC** [MrPrimate/tokenizer#56]
Currently it is only possible to set up a default background colour, it would be great to have the option to instead set up a default background image instead.

**Comment by kuzin** [comment]
+1 Additionally, setting a different 'default background' for each token type (hostile, npc, pc) would be awesome and a huge time saver.

**Comment by MrPrimate** [comment]
Partially in v4.2.2, background/texture layer per type to come.

**Comment by MrPrimate** [comment]
Now implemented.
