### ISSUE TITLE
When specifying Default BACKGROUND color with an alpha, it changes the transparency of the entire token

### ISSUE THREAD

**Issue by galaara98** [MrPrimate/tokenizer#63]
i tried to set the default background token background to #FFFFFF80, which i was hoping for the ring and the art to be fully opaque, and the white behind the ring to be roughly 50% transparent 80/FF (128/255)  

instead the whole token was approximately 50% transparent (i took it to the extreme and set it to #FFFFFF20 and yeah it is affecting the whole thing)

**Comment by MrPrimate** [comment]
I'm hoping the addition of a Transparency/Alpha slider and the ability to add coloured layers solves the usecase for you here. I _think_ I was able to replicate what you were after.
