### ISSUE TITLE
[Feature Request] 'Token Only' default setting

### ISSUE THREAD

**Issue by adisander** [MrPrimate/tokenizer#69]
A setting for whether the 'Token Only' toggle is enabled or disabled by default would be much appreciated, or a similar selection of functionality (such as disabling separate Avatar/Token fields, allowing both to be set at once with the same image, with the default method being that of either the Avatar or the Token fields).

**Comment by JordanRR** [comment]
I second that. I just downgraded to 3.5.1 because my players could not change their avatar anymore. Thank you!

**Comment by MrPrimate** [comment]
@JordanRR can you explain your issue, it seems unconnected to this.

**Comment by JordanRR** [comment]
The players cannot toggle the new "Token Only" mode that is on by default. So they can only modify their token, not their avatar. If I could allow it by default throught the settings, I would. The way I read @adisander comment, that's what they are asking for.

**Comment by MrPrimate** [comment]
Ah! Gotcha, I think there are about 3 requests in the original issue, but I see the problem with permissions - I will push a fix shortly

**Comment by adisander** [comment]
That and manually having uncheck 'Token Only' for each one I want to set adds work.

**Comment by MrPrimate** [comment]
Okay, I will push a fix shortly that will:
* Add a per-user setting in the Tokenizer module settings to choose token-only to on/off
* This will default to off (if you have played around with the toggle in the latest version it may already be set to something else)
* When you open tokenizer it will remember this setting, and you can toggle it there, but won't change the default.

I'll look at making improvements to:
* Allow avatar only
* Both use same image

**Comment by adisander** [comment]
Thank you!
