### ISSUE TITLE
Tokenizer is looking for the "profile" class but should be using the generig data-edit="img" tag instead

### ISSUE THREAD

**Issue by hakimassouane** [MrPrimate/tokenizer#71]
I was playing around with Giffyglyph's Quick Quest system and had troubles with the sheet not displaying tokenizer despite me being a GM and clicking on the avatar. Turns out, when comparing to dnd 5e system, that Tokenizer is actually searching for a `class="profile"` to trigger the Tokenizer UI.

Since all the systems are gonna use the `data-edit="img"` tag (to fire the base filepicker) but not the `class="profile"` I think Tokenizer should instead focus on searching for that tag (or at least as a complement of the `class="profile"`)

Open to discussion as it's not really a bug, but would help a few system builders out there

**Comment by MrPrimate** [comment]
Swapped in v3.6.2
