### ISSUE TITLE
Rendering Tokenizer - New Significant Delay

### ISSUE THREAD

**Issue by Jikkarr** [MrPrimate/tokenizer#72]
As of 3.6.3 I am experiencing a significant delay in rendering the tokenizer window. In the order of 34-35 seconds whereas before it was very quick.

Similarly adding a frame for the token is also taking an inordinate amount of time, sometimes in the order of 1 minute or more, whereas before it was also very quick.

The former delay is shown in the console log:
```
10:21:56.978 foundry.js:3055 Foundry VTT | Rendering Tokenizer
10:22:30.801 foundry.js:4662 Foundry VTT | Retrieved and compiled template modules/vtta-tokenizer/templates/tokenizer.hbs
````

Details:
Foundry 9.255
Tokenizer 3.6.3
Tested with on a fresh world (Dark Heresy 2E , WFRP4E &  DnD 5e system), no other modules active.

**Comment by MrPrimate** [comment]
What is your tokenizer setting "Directory for custom token frames" set to? ANd is there a lot of folders under it/a lot of images/files there?

**Comment by Jikkarr** [comment]
Ah-ha!

Thank you for such a quick follow-up. Both on the new world I created and pre-existing game worlds this field was left blank. Setting it to  `[data] tokenizer` does indeed bring it back to a normal response time.

**Comment by MrPrimate** [comment]
If it has not been set/ is blank I have pushed an update in v3.6.5 which should help.
