### ISSUE TITLE
[Enhancement] Allow Tokenizer to be Deactivated per user in Settings

### ISSUE THREAD

**Issue by avagdumortesin** [MrPrimate/tokenizer#74]
Having this tool has been invaluable for the players in my games, however I prefer to use the default browser (as I tend to make my tokens in an off-line tool, and simply upload them), which causes me to forget to enable it for my players at times.

I would like to be able to set it up when I'm setting up all of my other modules, but be able to deactivate it for me, instead of having to remember to hold the shift key. Having an option in Configure Settings > Module Settings > Tokenizer to "permanently" disable it for myself, but still allowing my players to use it would be awesome.

**Comment by MrPrimate** [comment]
This is in the latest version.
