### ISSUE TITLE
Tokenizer  log level set to ERROR but logs DEBUG messages

### ISSUE THREAD

**Issue by jocolamarco** [MrPrimate/tokenizer#76]
![image](https://user-images.githubusercontent.com/45291719/161431286-7dba6d93-94d7-4e22-b082-380d595c49eb.png)

![image](https://user-images.githubusercontent.com/45291719/161431301-793578f1-e592-4577-a010-e946ef5b81e4.png)

Versions:

![image](https://user-images.githubusercontent.com/45291719/161431310-3e3dcb43-7a19-4a71-9e14-63fcef4119a4.png)

![image](https://user-images.githubusercontent.com/45291719/161431338-f4ea1a62-f3d4-4cd9-ae8d-5aca6a57222f.png)

**Comment by MrPrimate** [comment]
This is fixed in the next release v3.6.5
