### ISSUE TITLE
Cannot find where tokenizer saved some images

### ISSUE THREAD

**Issue by JordanRR** [MrPrimate/tokenizer#77]
I'm hosting my game on the Forge using the latest stable updates to the Forge and for the module. Most of the tokens and avatars images are stored in the Tokenizer file. For some reason, a bunch of them are not, and I cannot find them anywhere. But the tokens and avatar are showing without issue when we play, so I'm stumped. 

Thanks!

**Comment by MrPrimate** [comment]
Can you provide a few examples - feel free to reach out to me on Discord rather than share image details publicly.

**Comment by JordanRR** [comment]
Sure, but I don't know what screenshot would be useful. Here is one example of an image I can see on the table but can't find in the usual folder (I also checked the NPC and Frames folders). I now realize that all the images from that user are not in the folder, so there probably is something there?

![image](https://user-images.githubusercontent.com/18445516/164206225-9ec1a4ca-cc36-40e1-aec2-c09f7cd5a854.png)
![image](https://user-images.githubusercontent.com/18445516/164206615-bdb6cc10-07f9-42f8-adf3-3871c90b4a9e.png)
![image](https://user-images.githubusercontent.com/18445516/164206350-7684c591-f48f-40bb-8fbe-b5b59e4fdd2d.png)

**Comment by MrPrimate** [comment]
What are the settings in the Tokenizer settings menu set to for location to save the various images?

**Comment by JordanRR** [comment]
![image](https://user-images.githubusercontent.com/18445516/164271286-42c62a04-e7aa-43c0-8fdf-22abcbef3b92.png)

I will find you on Discord, it might be easier than by forum!

**Comment by JordanRR** [comment]
Since the problem does not appear to be related to tekenizer, I'm talking with the Forge people. Thanks for your help, here and on Discord!
