### ISSUE TITLE
How to remove the OMFG frames?

### ISSUE THREAD

**Issue by megazver** [MrPrimate/tokenizer#78]
They are... not to my taste and they fill up the entire browser window when I open it to pick a frame I actually want.

If I just try removing them, the browser just looks like this:
![image](https://user-images.githubusercontent.com/9657370/168159232-755cb2ab-8589-47a9-95eb-2eb9225fd0b5.png)

Making them non-optional and not allowing their removal is... unideal.

**Comment by MrPrimate** [comment]
Stop using weasel words and ask for what you want, the option to disable OMFG frames. This is a reasonable request and will be included in the next release.

**Comment by MrPrimate** [comment]
In v3.6.8
