### ISSUE TITLE
Feature request: Custom Save Locations

### ISSUE THREAD

**Issue by kurisu-n** [MrPrimate/tokenizer#79]
I'd like to define the save location individually for each token, or at least have an option to save the token in the same location as the avatar is right now. 

Additionally, coping the image from avatar to token seems to create a new image of the avatar at the tokenizer folder, although not always.

**Comment by vt-tom** [comment]
I second this. A save as would be really cool.

**Comment by WBHarry** [comment]
I third this. I'd love to be able to have the path to the avatar and token unique and separate for an actor. Example:
**Avatar** <worldpath>/Avatars/Monsters/Undead/Zombies/Fastboi.png
**Token** <worldpath>/Tokens/Monsters/Undead/Zombies/Fastboi.png

**Comment by MrPrimate** [comment]
This is now a thing in 3.9.4

**Comment by dinotheextinct** [comment]
As far as I can see its not possible to save Token and Avatar image in separate folders. I also would appreciate such feature because it would make wildcard token images useful again.
