### ISSUE TITLE
Custom frames fail to mask. The layers below are completely hidden. Default frames work fine.

### ISSUE THREAD

**Issue by CatbotTsumi** [MrPrimate/tokenizer#80]
Custom frames fail to mask. The layers below are completely hidden. Default frames work fine. My token frames used to work for the years ive been using this, but now its starting breaking. im also managing to make the client/browser freeze with tokenizer by doing this and pressing more buttons.

These are layers im using.
![Before masking](https://i.imgur.com/LBdT0E6.png) 

And this is what happens.
![After masking](https://i.imgur.com/ShZLC1r.png)

There appear to be no errors in the console.

**Comment by MrPrimate** [comment]
Could you provide the frame you are using that definitely worked in the previous versions but not the latest one. Some frames it does have problems finding a mask for - but this should have been the case previously as well.

**Comment by MrPrimate** [comment]
Don't worry, I have managed to replicate, it looks like a side effect of using higher resolutions in the canvas data causes the mask detection to go wonky for more complex masks.

**Comment by MrPrimate** [comment]
Fixed in v3.8.1 (I hope) please let me know if this is not the case for you, and point me towards a copyof the frame.

**Comment by KellethDregar** [comment]
@MrPrimate Seeing this issue start happening again. Token border masks just make the image below disappear.

![image](https://user-images.githubusercontent.com/79947702/235393325-a2093f19-e19a-468a-81d3-fb0936e5ef07.png)
