### ISSUE TITLE
Adding compatibility for other game systems.

### ISSUE THREAD

**Issue by LianneKis** [MrPrimate/tokenizer#81]
I've encountered an issue while attempting to use Tokenizer on another system in Foundry.

Specifically, I wanted to use it in the DND3.5e system for character portraits but it seems the token image would not save and update once finished editing it. I'm not sure how this module couldn't be compatible with some other systems but it seems that something goes wrong when updating the token and I'm not given any error messages.

I hope this is a fixable issue, I otherwise really like using Tokenizer in the DND5e system.

**Comment by MrPrimate** [comment]
3.5e is actually an outlier here, it doesn't seem to support updating a token image via the standard `actor.update` call using the `token.img` data. I think this is probably a bug with the 3,5e system to deviate from the standard model for updating tokens on actors, and would log a bug with the system author.
