### ISSUE TITLE
901 by 1173 Pixel Images Freeze Tokenizer/Foundry

### ISSUE THREAD

**Issue by Tarbarian** [MrPrimate/tokenizer#82]
Don't ask me why, but Foundry reliably freeze when uploading images 901 pixels wide by 1173 pixels tall, like the attached black test image. I cannot prove crash logs or console output, as it freezes so thoroughly that neither can be accessed. I thought this would be some sort of aspect ratio issue but 1802 x 2346 doesn't reproduce the issue... I honestly don't know, but it bothers me. If you figure out the cause, please let me know.

![Test](https://user-images.githubusercontent.com/76751079/173205730-a9f727c8-a459-4822-819a-663f896b98ed.png)

**Comment by MrPrimate** [comment]
This is an amazing edge case! I think I have a fix and will update later today

**Comment by MrPrimate** [comment]
Fixed in v 3.8.4
