### ISSUE TITLE
Upgraded Module Causing weird behavior

### ISSUE THREAD

**Issue by neoanomally** [MrPrimate/tokenizer#83]
Foundry Version 9 Build 269
Pathfinder 2nd edition 3.10.4.11747
Tokenizer 3.8.4 (also issue was present in 3.8.2 / 3.8.1)

After upgrading I'm not able to add an avatar layer anymore. I can still add a token. However after it saves when you open up the avatar screen again, more weird behavior.
<img width="835" alt="image" src="https://user-images.githubusercontent.com/8324116/173244727-61ad3dcb-5673-4e8a-ab56-cfceeb4fcd19.png">

This is what happens after you add a token layer and then reopen the avatar within the PF2e Character sheet. It looks like the image opens the token image, but then adds another token ring around it. 
<img width="866" alt="image" src="https://user-images.githubusercontent.com/8324116/173244792-3bb47796-85c5-40a3-8b7d-201f5519e6fc.png">

**Comment by MrPrimate** [comment]
The avatar new layer/change required the toggling of the "Modify Token Only?" flag at the bottom left. If you want to mostly modify Tokens and Avatars, then you enable this by default in the module settings. (Under "Token only default")

The second issue is that Tokenizer now offsets images it finds a little and shrinks them to fit in the token ring so you can see more of the image. If this is not your desired behaviour, change the "Default Token Offset" value from `-35` to `0` in the module settings.
