### ISSUE TITLE
Tokenizer saves token, but not avatar PF1

### ISSUE THREAD

**Issue by davidoford** [MrPrimate/tokenizer#84]
Using latest PF1 system, the tokenizer no longer saves the avatar. I'll make a character, copy an image into my clipboard, paste it into tokenizer's avatar section, then post it into the tokenizer's token section, save it, and the avatar defaults to what it started as, but the token saves correctly.

**Comment by davidoford** [comment]
Sorry, I'm an idiot and for some reason "modify token only" slider was active

Closing this as a PEBKAC error

**Comment by MrPrimate** [comment]
I did change the default, sorry! You can switch it back to the old style where the avatar is always saved/modified in the module settings.
