### ISSUE TITLE
Not working?

### ISSUE THREAD

**Issue by arcanjl** [MrPrimate/tokenizer#86]
All of a sudden, it doesn't work. I double-click on it, and nothing.

**Comment by MrPrimate** [comment]
Can you answer the following questions please:

- what version of Foundry are you using?
- what system and system version are you using?
- what version of Tokenizer are you using?
- can you open the developer console (F12) and see if any error messages appear when you try to open tokenizer

**Comment by arcanjl** [comment]
Thank you, I found the issue with the help of discord. I was missing a folder in data folder. Thanks!
