### ISSUE TITLE
Masking Layer Cutting Improperly

### ISSUE THREAD

**Issue by KellethDregar** [MrPrimate/tokenizer#87]
For some reason the masking layer is cutting improperly in some of the latest versions. The issue seems to have begun on version 3.8.3 as when reverting back to version 3.8.2 I found that the issue is not present here.

3.8.2 or below
![image](https://user-images.githubusercontent.com/79947702/177467121-7eee9b19-9bf3-4987-b689-e74e8fda6f21.png)

3.8.3+
![image](https://user-images.githubusercontent.com/79947702/177468576-c2f08052-97b0-4361-aa9a-490e9bd0f451.png)

**Comment by MrPrimate** [comment]
In the settings you can revert to the old algorithm for mask detection which should work for this mask, at least as a work around for now

**Comment by MrPrimate** [comment]
Hopefully the custom masking coupled with the older algorithm will give you the tools you need for these now.
