### ISSUE TITLE
[Feature Request] Tintable Borders

### ISSUE THREAD

**Issue by LegoFed3** [MrPrimate/tokenizer#92]
While the module already supports custom borders, having to use external softwarve (e.g. GIMP) to tune their color (whenever one desires a certain style and doesn't have any version of approximately the right hue) half defeats the purpose of having a nice integrated token-making tool.
Would it be possible to make border layers tintable in more or less the same way as color layers (setting the underlying image's hue if nothing else)?
Or, at least, allow color layers to be masked on top of an underlying border layer (thus affecting its hue, if imperfectly)?

P.S.: thanks for making the module in the first place, it's a huge time saver.

**Comment by MrPrimate** [comment]
In v4.1.1. Enjoy!
