### ISSUE TITLE
Duplication / Merging

### ISSUE THREAD

**Issue by SolarisDevorak** [MrPrimate/tokenizer#93]
My tokens are doing something strange. I will try and explain as best I can.
I create the token as normal and it saves as it should. Upon the game reload, the token border as merged into one layer with the art and scaled down. A new border layer and background has also been added. I have attached an image that shows the issue.
As a note, I am working on the forge server.
![token issue](https://user-images.githubusercontent.com/96923884/181986939-bf27b0c7-c671-4d59-a814-111d12919420.png)

**Comment by MrPrimate** [comment]
This is because Tokenizer doesn't "remember layers". Once you save it creates a new image for you, with the layers merged. when you reopen it defaults to adding a border and shrinking the existing image a little bit. You can turn both of these options off in the settings.
