### ISSUE TITLE
Needs Updating for Version 10 Functionality

### ISSUE THREAD

**Issue by gmmatt** [MrPrimate/tokenizer#95]
(This is probably not needed, so feel free to delete/remove if you are already aware)
Does not function in version 10.  When attempting to open an image the following error generates:
"Cannot set properties of undefined (setting '_copy')

**Comment by MrPrimate** [comment]
Hmm, I was pretty sure this was now working with V10. Can you let me know your system, and more details about when this happens?

**Comment by gmmatt** [comment]
I disabled a couple of other modules and its working now. Dungeon Draw seems to be the culprit for breaking several things - and its not v10 compatible yet. So no worries. Thanks for taking the time to respond!
