### ISSUE TITLE
Tokenizer crashes Foundry when opening Explorer

### ISSUE THREAD

**Issue by Yuven91** [MrPrimate/tokenizer#97]
modules used: 
Foundry v10
Pathfinder 2e v4

when opening explorer through Tokenizer to import images foundry crashes
![image](https://user-images.githubusercontent.com/22319152/189611266-b18f63c4-131e-49f8-beff-35fa88be48ff.png)
![image](https://user-images.githubusercontent.com/22319152/189611398-d831ec28-1014-487a-8f08-c637854279f0.png)

**Comment by MrPrimate** [comment]
Are you using a browser or the Foundry client?
What exact version of path finder is it?
Windows 10 or 11?
Does it work in a world with another game system installed? (e.g. dnd5e)
