### ISSUE TITLE
Apply Prototype Token to scene tokens

### ISSUE THREAD

**Issue by Weissrolf** [MrPrimate/tokenizer#98]
Hello.

I may understand the option wrong, but should this not apply the prototype token settings to all scene tokens of the same kind? Currently it seem to do nothing (in v10)?!

Thanks for the great module! :-)

**Comment by MrPrimate** [comment]
AH, so this may be misnamed - it only applies the updated image to the scene tokens.

**Comment by Weissrolf** [comment]
Also a nice feature. Fortunately the module "Sidebar Context" offers a way to update all scene tokens to the prototype token settings. So we can have both. :-)

**Comment by MrPrimate** [comment]
The wording has been updated to reduce confusion.
