### ISSUE TITLE
Error when trying to use Tokenizer v10

### ISSUE THREAD

**Issue by west1778** [MrPrimate/tokenizer#99]
![image](https://user-images.githubusercontent.com/73608023/190277275-41e3547c-4390-4c37-b6b4-d5192bc4a236.png)

Getting this error message when trying to use Tokenizer.

**Comment by MrPrimate** [comment]
This looks like a duplicate of https://github.com/MrPrimate/tokenizer/issues/95

Please disable other modules and try again, Dungeon Draw was problematic last time.

**Comment by west1778** [comment]
So found the culprit using the Find the Culprit module. It's Combat Numbers. https://github.com/1000nettles/combat-numbers that was causing the issue.
